#!/bin/bash

# ResentSnapshot=$(ls -1 "$PoolPath/lower-"* | sort -r | head --lines=1)

ls_status() {
  if [ -d "$PoolPath" ]; then
    echo "$TargetPath is layersnapped!"
    i=0
    for f in lower-*; do
      i=$(expr $i + 1)
      echo $i: $(echo $f | cut -c 7-);
    done
  else
    echo "$TargetPath is not layersnapped."
  fi
}

#
# create new snapshot-layer
#

ls_snapshot() {
  # define
  Now=$(date "$DateFormat")
  UpperPath="$PoolPath/upper"
  LowerPath="$PoolPath/lower-$Now"
  WorkPath="$PoolPath/work"
  
  # do
  if [ ! -d "$PoolPath" ]; then
    # first snapshot
    mkdir -p "$PoolPath"
    mkdir "$WorkPath"
    mv    "$TargetPath" "$LowerPath"
    mkdir "$TargetPath"
  else
    # consecutive snapshots 
    umount "$TargetPath"
    mv "$UpperPath" "$LowerPath"
  fi
  mkdir "$UpperPath"

  # collect lower-paths
  LowerList=""
  for f in "$PoolPath/lower-"*; do
    LowerList=$LowerList:$(realpath $f)
  done
  LowerList=$(echo $LowerList | cut -c 2-)

  # mount
  mount -t overlay overlay -olowerdir="$LowerList",upperdir="$UpperPath",workdir="$WorkPath" "$TargetPath"
}

#
# merge with previous layer
#

ls_merge() {
  ls
}

#
# restore layer
#

ls_restore() {
  ls
}
