#!/bin/bash

# 
# show status and layers
#

ls_status() {
  setPoolVars
  if [ ! "$PoolMounted" == "true" ]; then
    ls_mount
    echo "layers have just been mounted."
  fi

  echo "LAYERSNAP: $TargetPath" consists of $(expr $LayerCount + 1) layers.
  
  i=1; for f in "$PoolPath/lower-"*; do
    layerStatusLine $i $f
    i=$(expr $i + 1)
  done
  layerStatusLine $(expr $LayerCount + 1) $UpperPath upper
}

#
# mount pool
#

ls_mount() {
  setPoolVars
  
  # mount
  mount -t overlay overlay -olowerdir="$LowerList",upperdir="$UpperPath",workdir="$WorkPath" "$TargetPath"
}

#
# create new snapshot-layer
#
# - unmount layers, except for first snapshot 
# - make lower-layer from target- or form upper-directory (on first snapshot)
# - create new empty upper directory
# - remount layers
#

ls_snapshot() {
  setPoolVars
  
  if [ ! -d "$PoolPath" ]; then
    ls_snapshot_first
  else
    ls_snapshot_consecutive
  fi
  mkdir "$UpperPath"
  ls_mount
}

ls_snapshot_first() {
  mkdir -p "$PoolPath"
  mkdir "$WorkPath"
  mv    "$TargetPath" "$LowerPath"
  mkdir "$TargetPath"
}

ls_snapshot_consecutive() {
  umount "$TargetPath"
  mv "$UpperPath" "$LowerPath"
}

#
# restore layer
#
# - let user select layer-Id to restore
# - merge layer-after-layer into lowest layer
# - make lowest layer the new target dir
# - clean up
#

ls_restore() {
  ls_status
  read -p "Snapshot ID to restore: " toLayerID

  umount "$TargetPath"
  rmdir  "$TargetPath"
    
  i=1
  for f in "$PoolPath/lower-"*; do
    # remember lowest layer and merge all upper layer into it
    if [ "$i" == 1 ]; then
      LowestPath="$f"
    else
      mergeLayersByPath "$f/" "$LowestPath"
    fi
    if [ "$i" == "$toLayerID" ]; then break; fi
    i=$(expr $i + 1)
  done
  
  mv "$LowestPath" "$TargetPath"
  rm -R "$PoolPath"
}


#
# merge layers
#
# - ask for layers to merge
# - 
#
#
#

ls_merge() {
  ls_status
  
  read -p "Merge layers starting from: " fromLayerID
  read -p "Merge layers ending with: " toLayerID
  echo "All layers between and including layers $fromLayerID and $toLayerID will be merged into layer $toLayerID."
  read -p "Enter 'merge' to confirm: " confirmation
  if [ ! "$confirmation" == "merge" ]; then
    echo "aborting."
    #return 2
  fi
  
  # find toLayer-path
  setToLayerPath
  
  i=1
  for f in "$PoolPath/lower-"*; do
    if [ "$i" -ge "$fromLayerID" ] && [ "$i" -lt "$toLayerID" ]; then
      mergeLayersByPath $f $toLayerPath
    elif [ "$i" -ge "$toLayerID" ]; then
      break
    fi
    i=$(expr $i + 1)
  done
  
  echo "done"
}

















