#!/bin/bash

# $(ls -1 $PoolDir | sort -r | head --lines=1)

ls_status() {
  if [ -d "$PoolDir" ]; then
    echo "$TargetDir is layersnapped!"
  else
    echo "$TargetDir is not layersnapped."
  fi
}

#
# create new snapshot-layer
#

ls_snapshot() {
  # --- DEFINE ---# 
  Now=$(date "$DateFormat")
  UpperDir="$PoolDir/upper"
  LowerDir="$PoolDir/lower-$now"
  LowerList=""; for f in lower-*; do Paths=$Paths:$(realpath $f); done
  WorkDir="$PoolDir/work"

  # --- WORK --- #
  if [ -d "$PoolDir" ]; then
    mkdir -p "$PoolDir"
    mkdir "$UpperDir"
    mkdir "$WorkDir"
    mv    "$TargetDir" "$LowerDir"
    mkdir "$TargetDir"
    mount -t overlay overlay -olowerdir="$LowerDir",upperdir="$UpperDir",workdir="$WorkDir" "$TargetDir" 
  else
    umount "$TargetDir"
    mv "$UpperDir" "$LowerDir"
    ResentSnapshot=$(ls -1 "$PoolDir/lower-"* | sort -r | head --lines=1)
    
  fi
}

#
# merge with previous layer
#

ls_merge() {
  ls
}

#
# restore layer
#

ls_restore() {
  ls
}
