#!/bin/bash

# "-" params
while [[ $# -gt 1 ]]
do
  key="$1"
  case $key in
    -m|--merge)
    MERGE="1" #"$2"
    shift
    ;;

    -r|--restore)
    RESTORE="1" #"$2"
    shift
    ;;
    
  esac
done

# last param
if [[ -n $1 ]]; then
  DIR=$1
fi

# http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash

echo "### r:$RESTORE m: $MERGE d: $DIR"
