#!/bin/bash

# "-" params
ACTION=status
while [[ $# -gt 1 ]]
do
  key="$1"
  case $key in
    -s|--snapshot)
    ACTION=snapshot #"$2"
    shift
    ;;

    -r|--restore)
    ACTION=restore #"$2"
    VALUE="$2"
    shift
    ;;

    -m|--merge)
    ACTION=merge #"$2"
    shift
    ;;
  esac
done

# last param
if [[ -n $1 ]]; then
  DIR=$1
else
  DIR=$(pwd)
fi

# http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash

echo "### $ACTION $VALUE $DIR"
